GET http://localhost:1234/movies

### Recover a movie by ID
GET http://localhost:1234/movies/6cf9ebbf-7c65-4387-92a5-0c841f255bed
### Recover all the movies
GET http://localhost:1234/movies?genre=fantasy

### To create a new movies
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The GodFather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Crime",
        "Drama"
    ]
}

### No validate request
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "123",
    "year": 123
}

### Delete movie
DELETE http://localhost:1234/movies/40ee4b5a-ade2-4be9-bab2-c53649cf2568
Content-Type: application/json


### Updata a movie
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "year" : 1991
}